---
sudo: false
language: ruby
cache: bundler
jdk:
  - oraclejdk8
rvm:
  - jruby-1.7.25
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE jdbc_streaming_db;'
before_script:
  - bundle exec rake vendor
script:
  - bundle exec rspec spec && bundle exec rspec spec --tag integration
